package com.github.thelonedevil.rpgoverhaul.weapons;

public enum CrystalType {
	NONE, FIRE, AIR, EARTH, WATER, PLASMA, SMELTING, SUN, MOON, ARIES, TAURUS, GEMINI, CANCER, LEO, VIRGO, LIBRA, SCORPIO, SAGITTARIUS, CAPRICORN, AQUARIUS, PISCES, DRAGON_FIRE, DRAGON_SKY, DRAGON_IRON, DRAGON_LIGHTNING, DRAGON_SHADOW, DRAGON_LIGHT, CREST_COURAGE, CREST_FRIENDSHIP, CREST_LOVE, CREST_SINCERITY, CREST_KNOWLEDGE, CREST_RELIABILITY, CREST_HOPE, CREST_LIGHT, CREST_KINDNESS
}
