package com.github.thelonedevil.rpgoverhaul;

import net.minecraft.item.Item;
import cpw.mods.fml.common.registry.GameRegistry;

public class MixedIngots {
	public static Item mixedIngot_Xiatherium_Farunese;
	public static Item mixedIngot_Xiatherium_Orobalt;
	public static Item mixedIngot_Xiatherium_Kiritorium;
	public static Item mixedIngot_Xiatherium_Asunalt;
	public static Item mixedIngot_Xiatherium_eruslalt;
	public static Item mixedIngot_Xiatherium_ithasium;
	public static Item mixedIngot_Xiatherium_ozestum;
	public static Item mixedIngot_Xiatherium_emodralt;
	public static Item mixedIngot_Xiatherium_evosum;
	public static Item mixedIngot_Xiatherium_nautrenese;
	public static Item mixedIngot_Xiatherium_axespium;
	public static Item mixedIngot_Xiatherium_ketsuekium;
	public static Item mixedIngot_Xiatherium_shikyolt;
	public static Item mixedIngot_Xiatherium_sakuralt;
	public static Item mixedIngot_Xiatherium_ayagrese;
	public static Item mixedIngot_Xiatherium_tenshirium;
	public static Item mixedIngot_Xiatherium_onecrum;
	public static Item mixedIngot_Xiatherium_gold;
	public static Item mixedIngot_Xiatherium_iron;
	public static Item mixedIngot_Farunese_Orobalt;
	public static Item mixedIngot_Farunese_Kiritorium;
	public static Item mixedIngot_Farunese_Asunalt;
	public static Item mixedIngot_Farunese_eruslalt;
	public static Item mixedIngot_Farunese_ithasium;
	public static Item mixedIngot_Farunese_ozestum;
	public static Item mixedIngot_Farunese_emodralt;
	public static Item mixedIngot_Farunese_evosum;
	public static Item mixedIngot_Farunese_nautrenese;
	public static Item mixedIngot_Farunese_axespium;
	public static Item mixedIngot_Farunese_ketsuekium;
	public static Item mixedIngot_Farunese_shikyolt;
	public static Item mixedIngot_Farunese_sakuralt;
	public static Item mixedIngot_Farunese_ayagrese;
	public static Item mixedIngot_Farunese_tenshirium;
	public static Item mixedIngot_Farunese_onecrum;
	public static Item mixedIngot_Farunese_gold;
	public static Item mixedIngot_Farunese_iron;
	public static Item mixedIngot_Orobalt_Kiritorium;
	public static Item mixedIngot_Orobalt_Asunalt;
	public static Item mixedIngot_Orobalt_eruslalt;
	public static Item mixedIngot_Orobalt_ithasium;
	public static Item mixedIngot_Orobalt_ozestum;
	public static Item mixedIngot_Orobalt_emodralt;
	public static Item mixedIngot_Orobalt_evosum;
	public static Item mixedIngot_Orobalt_nautrenese;
	public static Item mixedIngot_Orobalt_axespium;
	public static Item mixedIngot_Orobalt_ketsuekium;
	public static Item mixedIngot_Orobalt_shikyolt;
	public static Item mixedIngot_Orobalt_sakuralt;
	public static Item mixedIngot_Orobalt_ayagrese;
	public static Item mixedIngot_Orobalt_tenshirium;
	public static Item mixedIngot_Orobalt_onecrum;
	public static Item mixedIngot_Orobalt_gold;
	public static Item mixedIngot_Orobalt_iron;
	public static Item mixedIngot_Kiritorium_Asunalt;
	public static Item mixedIngot_Kiritorium_eruslalt;
	public static Item mixedIngot_Kiritorium_ithasium;
	public static Item mixedIngot_Kiritorium_ozestum;
	public static Item mixedIngot_Kiritorium_emodralt;
	public static Item mixedIngot_Kiritorium_evosum;
	public static Item mixedIngot_Kiritorium_nautrenese;
	public static Item mixedIngot_Kiritorium_axespium;
	public static Item mixedIngot_Kiritorium_ketsuekium;
	public static Item mixedIngot_Kiritorium_shikyolt;
	public static Item mixedIngot_Kiritorium_sakuralt;
	public static Item mixedIngot_Kiritorium_ayagrese;
	public static Item mixedIngot_Kiritorium_tenshirium;
	public static Item mixedIngot_Kiritorium_onecrum;
	public static Item mixedIngot_Kiritorium_gold;
	public static Item mixedIngot_Kiritorium_iron;
	public static Item mixedIngot_Asunalt_eruslalt;
	public static Item mixedIngot_Asunalt_ithasium;
	public static Item mixedIngot_Asunalt_ozestum;
	public static Item mixedIngot_Asunalt_emodralt;
	public static Item mixedIngot_Asunalt_evosum;
	public static Item mixedIngot_Asunalt_nautrenese;
	public static Item mixedIngot_Asunalt_axespium;
	public static Item mixedIngot_Asunalt_ketsuekium;
	public static Item mixedIngot_Asunalt_shikyolt;
	public static Item mixedIngot_Asunalt_sakuralt;
	public static Item mixedIngot_Asunalt_ayagrese;
	public static Item mixedIngot_Asunalt_tenshirium;
	public static Item mixedIngot_Asunalt_onecrum;
	public static Item mixedIngot_Asunalt_gold;
	public static Item mixedIngot_Asunalt_iron;
	public static Item mixedIngot_eruslalt_ithasium;
	public static Item mixedIngot_eruslalt_ozestum;
	public static Item mixedIngot_eruslalt_emodralt;
	public static Item mixedIngot_eruslalt_evosum;
	public static Item mixedIngot_eruslalt_nautrenese;
	public static Item mixedIngot_eruslalt_axespium;
	public static Item mixedIngot_eruslalt_ketsuekium;
	public static Item mixedIngot_eruslalt_shikyolt;
	public static Item mixedIngot_eruslalt_sakuralt;
	public static Item mixedIngot_eruslalt_ayagrese;
	public static Item mixedIngot_eruslalt_tenshirium;
	public static Item mixedIngot_eruslalt_onecrum;
	public static Item mixedIngot_eruslalt_gold;
	public static Item mixedIngot_eruslalt_iron;
	public static Item mixedIngot_ithasium_ozestum;
	public static Item mixedIngot_ithasium_emodralt;
	public static Item mixedIngot_ithasium_evosum;
	public static Item mixedIngot_ithasium_nautrenese;
	public static Item mixedIngot_ithasium_axespium;
	public static Item mixedIngot_ithasium_ketsuekium;
	public static Item mixedIngot_ithasium_shikyolt;
	public static Item mixedIngot_ithasium_sakuralt;
	public static Item mixedIngot_ithasium_ayagrese;
	public static Item mixedIngot_ithasium_tenshirium;
	public static Item mixedIngot_ithasium_onecrum;
	public static Item mixedIngot_ithasium_gold;
	public static Item mixedIngot_ithasium_iron;
	public static Item mixedIngot_ozestum_emodralt;
	public static Item mixedIngot_ozestum_evosum;
	public static Item mixedIngot_ozestum_nautrenese;
	public static Item mixedIngot_ozestum_axespium;
	public static Item mixedIngot_ozestum_ketsuekium;
	public static Item mixedIngot_ozestum_shikyolt;
	public static Item mixedIngot_ozestum_sakuralt;
	public static Item mixedIngot_ozestum_ayagrese;
	public static Item mixedIngot_ozestum_tenshirium;
	public static Item mixedIngot_ozestum_onecrum;
	public static Item mixedIngot_ozestum_gold;
	public static Item mixedIngot_ozestum_iron;
	public static Item mixedIngot_emodralt_evosum;
	public static Item mixedIngot_emodralt_nautrenese;
	public static Item mixedIngot_emodralt_axespium;
	public static Item mixedIngot_emodralt_ketsuekium;
	public static Item mixedIngot_emodralt_shikyolt;
	public static Item mixedIngot_emodralt_sakuralt;
	public static Item mixedIngot_emodralt_ayagrese;
	public static Item mixedIngot_emodralt_tenshirium;
	public static Item mixedIngot_emodralt_onecrum;
	public static Item mixedIngot_emodralt_gold;
	public static Item mixedIngot_emodralt_iron;
	public static Item mixedIngot_evosum_nautrenese;
	public static Item mixedIngot_evosum_axespium;
	public static Item mixedIngot_evosum_ketsuekium;
	public static Item mixedIngot_evosum_shikyolt;
	public static Item mixedIngot_evosum_sakuralt;
	public static Item mixedIngot_evosum_ayagrese;
	public static Item mixedIngot_evosum_tenshirium;
	public static Item mixedIngot_evosum_onecrum;
	public static Item mixedIngot_evosum_gold;
	public static Item mixedIngot_evosum_iron;
	public static Item mixedIngot_nautrenese_axespium;
	public static Item mixedIngot_nautrenese_ketsuekium;
	public static Item mixedIngot_nautrenese_shikyolt;
	public static Item mixedIngot_nautrenese_sakuralt;
	public static Item mixedIngot_nautrenese_ayagrese;
	public static Item mixedIngot_nautrenese_tenshirium;
	public static Item mixedIngot_nautrenese_onecrum;
	public static Item mixedIngot_nautrenese_gold;
	public static Item mixedIngot_nautrenese_iron;
	public static Item mixedIngot_axespium_ketsuekium;
	public static Item mixedIngot_axespium_shikyolt;
	public static Item mixedIngot_axespium_sakuralt;
	public static Item mixedIngot_axespium_ayagrese;
	public static Item mixedIngot_axespium_tenshirium;
	public static Item mixedIngot_axespium_onecrum;
	public static Item mixedIngot_axespium_gold;
	public static Item mixedIngot_axespium_iron;
	public static Item mixedIngot_ketsuekium_shikyolt;
	public static Item mixedIngot_ketsuekium_sakuralt;
	public static Item mixedIngot_ketsuekium_ayagrese;
	public static Item mixedIngot_ketsuekium_tenshirium;
	public static Item mixedIngot_ketsuekium_onecrum;
	public static Item mixedIngot_ketsuekium_gold;
	public static Item mixedIngot_ketsuekium_iron;
	public static Item mixedIngot_shikyolt_sakuralt;
	public static Item mixedIngot_shikyolt_ayagrese;
	public static Item mixedIngot_shikyolt_tenshirium;
	public static Item mixedIngot_shikyolt_onecrum;
	public static Item mixedIngot_shikyolt_gold;
	public static Item mixedIngot_shikyolt_iron;
	public static Item mixedIngot_sakuralt_ayagrese;
	public static Item mixedIngot_sakuralt_tenshirium;
	public static Item mixedIngot_sakuralt_onecrum;
	public static Item mixedIngot_sakuralt_gold;
	public static Item mixedIngot_sakuralt_iron;
	public static Item mixedIngot_ayagrese_tenshirium;
	public static Item mixedIngot_ayagrese_onecrum;
	public static Item mixedIngot_ayagrese_gold;
	public static Item mixedIngot_ayagrese_iron;
	public static Item mixedIngot_tenshirium_onecrum;
	public static Item mixedIngot_tenshirium_gold;
	public static Item mixedIngot_tenshirium_iron;
	public static Item mixedIngot_onecrum_gold;
	public static Item mixedIngot_onecrum_iron;
	public static Item mixedIngot_gold_iron;

	private static String name1 = "mixedIngot_Xiatherium_Farunese";
	private static String name2 = "mixedIngot_Xiatherium_Orobalt";
	private static String name3 = "mixedIngot_Xiatherium_Kiritorium";
	private static String name4 = "mixedIngot_Xiatherium_Asunalt";
	private static String name5 = "mixedIngot_Xiatherium_eruslalt";
	private static String name6 = "mixedIngot_Xiatherium_ithasium";
	private static String name7 = "mixedIngot_Xiatherium_ozestum";
	private static String name8 = "mixedIngot_Xiatherium_emodralt";
	private static String name9 = "mixedIngot_Xiatherium_evosum";
	private static String name10 = "mixedIngot_Xiatherium_nautrenese";
	private static String name11 = "mixedIngot_Xiatherium_axespium";
	private static String name12 = "mixedIngot_Xiatherium_ketsuekium";
	private static String name13 = "mixedIngot_Xiatherium_shikyolt";
	private static String name14 = "mixedIngot_Xiatherium_sakuralt";
	private static String name15 = "mixedIngot_Xiatherium_ayagrese";
	private static String name16 = "mixedIngot_Xiatherium_tenshirium";
	private static String name17 = "mixedIngot_Xiatherium_onecrum";
	private static String name18 = "mixedIngot_Xiatherium_gold";
	private static String name19 = "mixedIngot_Xiatherium_iron";
	private static String name20 = "mixedIngot_Farunese_Orobalt";
	private static String name21 = "mixedIngot_Farunese_Kiritorium";
	private static String name22 = "mixedIngot_Farunese_Asunalt";
	private static String name23 = "mixedIngot_Farunese_eruslalt";
	private static String name24 = "mixedIngot_Farunese_ithasium";
	private static String name25 = "mixedIngot_Farunese_ozestum";
	private static String name26 = "mixedIngot_Farunese_emodralt";
	private static String name27 = "mixedIngot_Farunese_evosum";
	private static String name28 = "mixedIngot_Farunese_nautrenese";
	private static String name29 = "mixedIngot_Farunese_axespium";
	private static String name30 = "mixedIngot_Farunese_ketsuekium";
	private static String name31 = "mixedIngot_Farunese_shikyolt";
	private static String name32 = "mixedIngot_Farunese_sakuralt";
	private static String name33 = "mixedIngot_Farunese_ayagrese";
	private static String name34 = "mixedIngot_Farunese_tenshirium";
	private static String name35 = "mixedIngot_Farunese_onecrum";
	private static String name36 = "mixedIngot_Farunese_gold";
	private static String name37 = "mixedIngot_Farunese_iron";
	private static String name38 = "mixedIngot_Orobalt_Kiritorium";
	private static String name39 = "mixedIngot_Orobalt_Asunalt";
	private static String name40 = "mixedIngot_Orobalt_eruslalt";
	private static String name41 = "mixedIngot_Orobalt_ithasium";
	private static String name42 = "mixedIngot_Orobalt_ozestum";
	private static String name43 = "mixedIngot_Orobalt_emodralt";
	private static String name44 = "mixedIngot_Orobalt_evosum";
	private static String name45 = "mixedIngot_Orobalt_nautrenese";
	private static String name46 = "mixedIngot_Orobalt_axespium";
	private static String name47 = "mixedIngot_Orobalt_ketsuekium";
	private static String name48 = "mixedIngot_Orobalt_shikyolt";
	private static String name49 = "mixedIngot_Orobalt_sakuralt";
	private static String name50 = "mixedIngot_Orobalt_ayagrese";
	private static String name51 = "mixedIngot_Orobalt_tenshirium";
	private static String name52 = "mixedIngot_Orobalt_onecrum";
	private static String name53 = "mixedIngot_Orobalt_gold";
	private static String name54 = "mixedIngot_Orobalt_iron";
	private static String name55 = "mixedIngot_Kiritorium_Asunalt";
	private static String name56 = "mixedIngot_Kiritorium_eruslalt";
	private static String name57 = "mixedIngot_Kiritorium_ithasium";
	private static String name58 = "mixedIngot_Kiritorium_ozestum";
	private static String name59 = "mixedIngot_Kiritorium_emodralt";
	private static String name60 = "mixedIngot_Kiritorium_evosum";
	private static String name61 = "mixedIngot_Kiritorium_nautrenese";
	private static String name62 = "mixedIngot_Kiritorium_axespium";
	private static String name63 = "mixedIngot_Kiritorium_ketsuekium";
	private static String name64 = "mixedIngot_Kiritorium_shikyolt";
	private static String name65 = "mixedIngot_Kiritorium_sakuralt";
	private static String name66 = "mixedIngot_Kiritorium_ayagrese";
	private static String name67 = "mixedIngot_Kiritorium_tenshirium";
	private static String name68 = "mixedIngot_Kiritorium_onecrum";
	private static String name69 = "mixedIngot_Kiritorium_gold";
	private static String name70 = "mixedIngot_Kiritorium_iron";
	private static String name71 = "mixedIngot_Asunalt_eruslalt";
	private static String name72 = "mixedIngot_Asunalt_ithasium";
	private static String name73 = "mixedIngot_Asunalt_ozestum";
	private static String name74 = "mixedIngot_Asunalt_emodralt";
	private static String name75 = "mixedIngot_Asunalt_evosum";
	private static String name76 = "mixedIngot_Asunalt_nautrenese";
	private static String name77 = "mixedIngot_Asunalt_axespium";
	private static String name78 = "mixedIngot_Asunalt_ketsuekium";
	private static String name79 = "mixedIngot_Asunalt_shikyolt";
	private static String name80 = "mixedIngot_Asunalt_sakuralt";
	private static String name81 = "mixedIngot_Asunalt_ayagrese";
	private static String name82 = "mixedIngot_Asunalt_tenshirium";
	private static String name83 = "mixedIngot_Asunalt_onecrum";
	private static String name84 = "mixedIngot_Asunalt_gold";
	private static String name85 = "mixedIngot_Asunalt_iron";
	private static String name86 = "mixedIngot_eruslalt_ithasium";
	private static String name87 = "mixedIngot_eruslalt_ozestum";
	private static String name88 = "mixedIngot_eruslalt_emodralt";
	private static String name89 = "mixedIngot_eruslalt_evosum";
	private static String name90 = "mixedIngot_eruslalt_nautrenese";
	private static String name91 = "mixedIngot_eruslalt_axespium";
	private static String name92 = "mixedIngot_eruslalt_ketsuekium";
	private static String name93 = "mixedIngot_eruslalt_shikyolt";
	private static String name94 = "mixedIngot_eruslalt_sakuralt";
	private static String name95 = "mixedIngot_eruslalt_ayagrese";
	private static String name96 = "mixedIngot_eruslalt_tenshirium";
	private static String name97 = "mixedIngot_eruslalt_onecrum";
	private static String name98 = "mixedIngot_eruslalt_gold";
	private static String name99 = "mixedIngot_eruslalt_iron";
	private static String name100 = "mixedIngot_ithasium_ozestum";
	private static String name101 = "mixedIngot_ithasium_emodralt";
	private static String name102 = "mixedIngot_ithasium_evosum";
	private static String name103 = "mixedIngot_ithasium_nautrenese";
	private static String name104 = "mixedIngot_ithasium_axespium";
	private static String name105 = "mixedIngot_ithasium_ketsuekium";
	private static String name106 = "mixedIngot_ithasium_shikyolt";
	private static String name107 = "mixedIngot_ithasium_sakuralt";
	private static String name108 = "mixedIngot_ithasium_ayagrese";
	private static String name109 = "mixedIngot_ithasium_tenshirium";
	private static String name110 = "mixedIngot_ithasium_onecrum";
	private static String name111 = "mixedIngot_ithasium_gold";
	private static String name112 = "mixedIngot_ithasium_iron";
	private static String name113 = "mixedIngot_ozestum_emodralt";
	private static String name114 = "mixedIngot_ozestum_evosum";
	private static String name115 = "mixedIngot_ozestum_nautrenese";
	private static String name116 = "mixedIngot_ozestum_axespium";
	private static String name117 = "mixedIngot_ozestum_ketsuekium";
	private static String name118 = "mixedIngot_ozestum_shikyolt";
	private static String name119 = "mixedIngot_ozestum_sakuralt";
	private static String name120 = "mixedIngot_ozestum_ayagrese";
	private static String name121 = "mixedIngot_ozestum_tenshirium";
	private static String name122 = "mixedIngot_ozestum_onecrum";
	private static String name123 = "mixedIngot_ozestum_gold";
	private static String name124 = "mixedIngot_ozestum_iron";
	private static String name125 = "mixedIngot_emodralt_evosum";
	private static String name126 = "mixedIngot_emodralt_nautrenese";
	private static String name127 = "mixedIngot_emodralt_axespium";
	private static String name128 = "mixedIngot_emodralt_ketsuekium";
	private static String name129 = "mixedIngot_emodralt_shikyolt";
	private static String name130 = "mixedIngot_emodralt_sakuralt";
	private static String name131 = "mixedIngot_emodralt_ayagrese";
	private static String name132 = "mixedIngot_emodralt_tenshirium";
	private static String name133 = "mixedIngot_emodralt_onecrum";
	private static String name134 = "mixedIngot_emodralt_gold";
	private static String name135 = "mixedIngot_emodralt_iron";
	private static String name136 = "mixedIngot_evosum_nautrenese";
	private static String name137 = "mixedIngot_evosum_axespium";
	private static String name138 = "mixedIngot_evosum_ketsuekium";
	private static String name139 = "mixedIngot_evosum_shikyolt";
	private static String name140 = "mixedIngot_evosum_sakuralt";
	private static String name141 = "mixedIngot_evosum_ayagrese";
	private static String name142 = "mixedIngot_evosum_tenshirium";
	private static String name143 = "mixedIngot_evosum_onecrum";
	private static String name144 = "mixedIngot_evosum_gold";
	private static String name145 = "mixedIngot_evosum_iron";
	private static String name146 = "mixedIngot_nautrenese_axespium";
	private static String name147 = "mixedIngot_nautrenese_ketsuekium";
	private static String name148 = "mixedIngot_nautrenese_shikyolt";
	private static String name149 = "mixedIngot_nautrenese_sakuralt";
	private static String name150 = "mixedIngot_nautrenese_ayagrese";
	private static String name151 = "mixedIngot_nautrenese_tenshirium";
	private static String name152 = "mixedIngot_nautrenese_onecrum";
	private static String name153 = "mixedIngot_nautrenese_gold";
	private static String name154 = "mixedIngot_nautrenese_iron";
	private static String name155 = "mixedIngot_axespium_ketsuekium";
	private static String name156 = "mixedIngot_axespium_shikyolt";
	private static String name157 = "mixedIngot_axespium_sakuralt";
	private static String name158 = "mixedIngot_axespium_ayagrese";
	private static String name159 = "mixedIngot_axespium_tenshirium";
	private static String name160 = "mixedIngot_axespium_onecrum";
	private static String name161 = "mixedIngot_axespium_gold";
	private static String name162 = "mixedIngot_axespium_iron";
	private static String name163 = "mixedIngot_ketsuekium_shikyolt";
	private static String name164 = "mixedIngot_ketsuekium_sakuralt";
	private static String name165 = "mixedIngot_ketsuekium_ayagrese";
	private static String name166 = "mixedIngot_ketsuekium_tenshirium";
	private static String name167 = "mixedIngot_ketsuekium_onecrum";
	private static String name168 = "mixedIngot_ketsuekium_gold";
	private static String name169 = "mixedIngot_ketsuekium_iron";
	private static String name170 = "mixedIngot_shikyolt_sakuralt";
	private static String name171 = "mixedIngot_shikyolt_ayagrese";
	private static String name172 = "mixedIngot_shikyolt_tenshirium";
	private static String name173 = "mixedIngot_shikyolt_onecrum";
	private static String name174 = "mixedIngot_shikyolt_gold";
	private static String name175 = "mixedIngot_shikyolt_iron";
	private static String name176 = "mixedIngot_sakuralt_ayagrese";
	private static String name177 = "mixedIngot_sakuralt_tenshirium";
	private static String name178 = "mixedIngot_sakuralt_onecrum";
	private static String name179 = "mixedIngot_sakuralt_gold";
	private static String name180 = "mixedIngot_sakuralt_iron";
	private static String name181 = "mixedIngot_ayagrese_tenshirium";
	private static String name182 = "mixedIngot_ayagrese_onecrum";
	private static String name183 = "mixedIngot_ayagrese_gold";
	private static String name184 = "mixedIngot_ayagrese_iron";
	private static String name185 = "mixedIngot_tenshirium_onecrum";
	private static String name186 = "mixedIngot_tenshirium_gold";
	private static String name187 = "mixedIngot_tenshirium_iron";
	private static String name188 = "mixedIngot_onecrum_gold";
	private static String name189 = "mixedIngot_onecrum_iron";
	private static String name190 = "mixedIngot_gold_iron";

	public static void init() {
		mixedIngot_Xiatherium_Farunese = new Item().setUnlocalizedName(name1).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Xiatherium_Orobalt = new Item().setUnlocalizedName(name2).setTextureName(RPGOMain.MODID + ":" + name2).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Xiatherium_Kiritorium = new Item().setUnlocalizedName(name3).setTextureName(RPGOMain.MODID + ":" + name3).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Xiatherium_Asunalt = new Item().setUnlocalizedName(name4).setTextureName(RPGOMain.MODID + ":" + name4).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Xiatherium_eruslalt = new Item().setUnlocalizedName(name5).setTextureName(RPGOMain.MODID + ":" + name5).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Xiatherium_ithasium = new Item().setUnlocalizedName(name6).setTextureName(RPGOMain.MODID + ":" + name6).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Xiatherium_ozestum = new Item().setUnlocalizedName(name7).setTextureName(RPGOMain.MODID + ":" + name7).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Xiatherium_emodralt = new Item().setUnlocalizedName(name8).setTextureName(RPGOMain.MODID + ":" + name8).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Xiatherium_evosum = new Item().setUnlocalizedName(name9).setTextureName(RPGOMain.MODID + ":" + name9).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Xiatherium_nautrenese = new Item().setUnlocalizedName(name10).setTextureName(RPGOMain.MODID + ":" + name10).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Xiatherium_axespium = new Item().setUnlocalizedName(name11).setTextureName(RPGOMain.MODID + ":" + name11).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Xiatherium_ketsuekium = new Item().setUnlocalizedName(name12).setTextureName(RPGOMain.MODID + ":" + name12).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Xiatherium_shikyolt = new Item().setUnlocalizedName(name13).setTextureName(RPGOMain.MODID + ":" + name13).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Xiatherium_sakuralt = new Item().setUnlocalizedName(name14).setTextureName(RPGOMain.MODID + ":" + name14).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Xiatherium_ayagrese = new Item().setUnlocalizedName(name15).setTextureName(RPGOMain.MODID + ":" + name15).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Xiatherium_tenshirium = new Item().setUnlocalizedName(name16).setTextureName(RPGOMain.MODID + ":" + name16).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Xiatherium_onecrum = new Item().setUnlocalizedName(name17).setTextureName(RPGOMain.MODID + ":" + name17).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Xiatherium_gold = new Item().setUnlocalizedName(name18).setTextureName(RPGOMain.MODID + ":" + name18).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Xiatherium_iron = new Item().setUnlocalizedName(name19).setTextureName(RPGOMain.MODID + ":" + name19).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Farunese_Orobalt = new Item().setUnlocalizedName(name20).setTextureName(RPGOMain.MODID + ":" + name20).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Farunese_Kiritorium = new Item().setUnlocalizedName(name21).setTextureName(RPGOMain.MODID + ":" + name21).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Farunese_Asunalt = new Item().setUnlocalizedName(name22).setTextureName(RPGOMain.MODID + ":" + name22).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Farunese_eruslalt = new Item().setUnlocalizedName(name23).setTextureName(RPGOMain.MODID + ":" + name23).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Farunese_ithasium = new Item().setUnlocalizedName(name24).setTextureName(RPGOMain.MODID + ":" + name24).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Farunese_ozestum = new Item().setUnlocalizedName(name25).setTextureName(RPGOMain.MODID + ":" + name25).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Farunese_emodralt = new Item().setUnlocalizedName(name26).setTextureName(RPGOMain.MODID + ":" + name26).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Farunese_evosum = new Item().setUnlocalizedName(name27).setTextureName(RPGOMain.MODID + ":" + name27).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Farunese_nautrenese = new Item().setUnlocalizedName(name28).setTextureName(RPGOMain.MODID + ":" + name28).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Farunese_axespium = new Item().setUnlocalizedName(name29).setTextureName(RPGOMain.MODID + ":" + name29).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Farunese_ketsuekium = new Item().setUnlocalizedName(name30).setTextureName(RPGOMain.MODID + ":" + name30).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Farunese_shikyolt = new Item().setUnlocalizedName(name31).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Farunese_sakuralt = new Item().setUnlocalizedName(name32).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Farunese_ayagrese = new Item().setUnlocalizedName(name33).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Farunese_tenshirium = new Item().setUnlocalizedName(name34).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Farunese_onecrum = new Item().setUnlocalizedName(name35).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Farunese_gold = new Item().setUnlocalizedName(name36).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Farunese_iron = new Item().setUnlocalizedName(name37).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Orobalt_Kiritorium = new Item().setUnlocalizedName(name38).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Orobalt_Asunalt = new Item().setUnlocalizedName(name39).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Orobalt_eruslalt = new Item().setUnlocalizedName(name40).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Orobalt_ithasium = new Item().setUnlocalizedName(name41).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Orobalt_ozestum = new Item().setUnlocalizedName(name42).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Orobalt_emodralt = new Item().setUnlocalizedName(name43).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Orobalt_evosum = new Item().setUnlocalizedName(name44).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Orobalt_nautrenese = new Item().setUnlocalizedName(name45).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Orobalt_axespium = new Item().setUnlocalizedName(name46).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Orobalt_ketsuekium = new Item().setUnlocalizedName(name47).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Orobalt_shikyolt = new Item().setUnlocalizedName(name48).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Orobalt_sakuralt = new Item().setUnlocalizedName(name49).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Orobalt_ayagrese = new Item().setUnlocalizedName(name50).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Orobalt_tenshirium = new Item().setUnlocalizedName(name51).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Orobalt_onecrum = new Item().setUnlocalizedName(name52).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Orobalt_gold = new Item().setUnlocalizedName(name53).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Orobalt_iron = new Item().setUnlocalizedName(name54).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Kiritorium_Asunalt = new Item().setUnlocalizedName(name55).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Kiritorium_eruslalt = new Item().setUnlocalizedName(name56).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Kiritorium_ithasium = new Item().setUnlocalizedName(name57).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Kiritorium_ozestum = new Item().setUnlocalizedName(name58).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Kiritorium_emodralt = new Item().setUnlocalizedName(name59).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Kiritorium_evosum = new Item().setUnlocalizedName(name60).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Kiritorium_nautrenese = new Item().setUnlocalizedName(name61).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Kiritorium_axespium = new Item().setUnlocalizedName(name62).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Kiritorium_ketsuekium = new Item().setUnlocalizedName(name63).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Kiritorium_shikyolt = new Item().setUnlocalizedName(name64).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Kiritorium_sakuralt = new Item().setUnlocalizedName(name65).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Kiritorium_ayagrese = new Item().setUnlocalizedName(name66).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Kiritorium_tenshirium = new Item().setUnlocalizedName(name67).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Kiritorium_onecrum = new Item().setUnlocalizedName(name68).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Kiritorium_gold = new Item().setUnlocalizedName(name69).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Kiritorium_iron = new Item().setUnlocalizedName(name70).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Asunalt_eruslalt = new Item().setUnlocalizedName(name71).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Asunalt_ithasium = new Item().setUnlocalizedName(name72).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Asunalt_ozestum = new Item().setUnlocalizedName(name73).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Asunalt_emodralt = new Item().setUnlocalizedName(name74).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Asunalt_evosum = new Item().setUnlocalizedName(name75).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Asunalt_nautrenese = new Item().setUnlocalizedName(name76).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Asunalt_axespium = new Item().setUnlocalizedName(name77).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Asunalt_ketsuekium = new Item().setUnlocalizedName(name78).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Asunalt_shikyolt = new Item().setUnlocalizedName(name79).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Asunalt_sakuralt = new Item().setUnlocalizedName(name80).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Asunalt_ayagrese = new Item().setUnlocalizedName(name81).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Asunalt_tenshirium = new Item().setUnlocalizedName(name82).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Asunalt_onecrum = new Item().setUnlocalizedName(name83).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Asunalt_gold = new Item().setUnlocalizedName(name84).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_Asunalt_iron = new Item().setUnlocalizedName(name85).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_eruslalt_ithasium = new Item().setUnlocalizedName(name86).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_eruslalt_ozestum = new Item().setUnlocalizedName(name87).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_eruslalt_emodralt = new Item().setUnlocalizedName(name88).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_eruslalt_evosum = new Item().setUnlocalizedName(name89).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_eruslalt_nautrenese = new Item().setUnlocalizedName(name90).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_eruslalt_axespium = new Item().setUnlocalizedName(name91).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_eruslalt_ketsuekium = new Item().setUnlocalizedName(name92).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_eruslalt_shikyolt = new Item().setUnlocalizedName(name93).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_eruslalt_sakuralt = new Item().setUnlocalizedName(name94).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_eruslalt_ayagrese = new Item().setUnlocalizedName(name95).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_eruslalt_tenshirium = new Item().setUnlocalizedName(name96).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_eruslalt_onecrum = new Item().setUnlocalizedName(name97).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_eruslalt_gold = new Item().setUnlocalizedName(name98).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_eruslalt_iron = new Item().setUnlocalizedName(name99).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_ithasium_ozestum = new Item().setUnlocalizedName(name100).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_ithasium_emodralt = new Item().setUnlocalizedName(name101).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_ithasium_evosum = new Item().setUnlocalizedName(name102).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_ithasium_nautrenese = new Item().setUnlocalizedName(name103).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_ithasium_axespium = new Item().setUnlocalizedName(name104).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_ithasium_ketsuekium = new Item().setUnlocalizedName(name105).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_ithasium_shikyolt = new Item().setUnlocalizedName(name106).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_ithasium_sakuralt = new Item().setUnlocalizedName(name107).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_ithasium_ayagrese = new Item().setUnlocalizedName(name108).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_ithasium_tenshirium = new Item().setUnlocalizedName(name109).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_ithasium_onecrum = new Item().setUnlocalizedName(name110).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_ithasium_gold = new Item().setUnlocalizedName(name111).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_ithasium_iron = new Item().setUnlocalizedName(name112).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_ozestum_emodralt = new Item().setUnlocalizedName(name113).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_ozestum_evosum = new Item().setUnlocalizedName(name114).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_ozestum_nautrenese = new Item().setUnlocalizedName(name115).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_ozestum_axespium = new Item().setUnlocalizedName(name116).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_ozestum_ketsuekium = new Item().setUnlocalizedName(name117).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_ozestum_shikyolt = new Item().setUnlocalizedName(name118).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_ozestum_sakuralt = new Item().setUnlocalizedName(name119).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_ozestum_ayagrese = new Item().setUnlocalizedName(name120).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_ozestum_tenshirium = new Item().setUnlocalizedName(name121).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_ozestum_onecrum = new Item().setUnlocalizedName(name122).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_ozestum_gold = new Item().setUnlocalizedName(name123).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_ozestum_iron = new Item().setUnlocalizedName(name124).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_emodralt_evosum = new Item().setUnlocalizedName(name125).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_emodralt_nautrenese = new Item().setUnlocalizedName(name126).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_emodralt_axespium = new Item().setUnlocalizedName(name127).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_emodralt_ketsuekium = new Item().setUnlocalizedName(name128).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_emodralt_shikyolt = new Item().setUnlocalizedName(name129).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_emodralt_sakuralt = new Item().setUnlocalizedName(name130).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_emodralt_ayagrese = new Item().setUnlocalizedName(name131).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_emodralt_tenshirium = new Item().setUnlocalizedName(name132).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_emodralt_onecrum = new Item().setUnlocalizedName(name133).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_emodralt_gold = new Item().setUnlocalizedName(name134).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_emodralt_iron = new Item().setUnlocalizedName(name135).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_evosum_nautrenese = new Item().setUnlocalizedName(name136).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_evosum_axespium = new Item().setUnlocalizedName(name137).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_evosum_ketsuekium = new Item().setUnlocalizedName(name138).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_evosum_shikyolt = new Item().setUnlocalizedName(name139).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_evosum_sakuralt = new Item().setUnlocalizedName(name140).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_evosum_ayagrese = new Item().setUnlocalizedName(name141).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_evosum_tenshirium = new Item().setUnlocalizedName(name142).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_evosum_onecrum = new Item().setUnlocalizedName(name143).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_evosum_gold = new Item().setUnlocalizedName(name144).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_evosum_iron = new Item().setUnlocalizedName(name145).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_nautrenese_axespium = new Item().setUnlocalizedName(name146).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_nautrenese_ketsuekium = new Item().setUnlocalizedName(name147).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_nautrenese_shikyolt = new Item().setUnlocalizedName(name148).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_nautrenese_sakuralt = new Item().setUnlocalizedName(name149).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_nautrenese_ayagrese = new Item().setUnlocalizedName(name150).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_nautrenese_tenshirium = new Item().setUnlocalizedName(name151).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_nautrenese_onecrum = new Item().setUnlocalizedName(name152).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_nautrenese_gold = new Item().setUnlocalizedName(name153).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_nautrenese_iron = new Item().setUnlocalizedName(name154).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_axespium_ketsuekium = new Item().setUnlocalizedName(name155).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_axespium_shikyolt = new Item().setUnlocalizedName(name156).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_axespium_sakuralt = new Item().setUnlocalizedName(name157).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_axespium_ayagrese = new Item().setUnlocalizedName(name158).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_axespium_tenshirium = new Item().setUnlocalizedName(name159).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_axespium_onecrum = new Item().setUnlocalizedName(name160).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_axespium_gold = new Item().setUnlocalizedName(name161).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_axespium_iron = new Item().setUnlocalizedName(name162).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_ketsuekium_shikyolt = new Item().setUnlocalizedName(name163).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_ketsuekium_sakuralt = new Item().setUnlocalizedName(name164).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_ketsuekium_ayagrese = new Item().setUnlocalizedName(name165).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_ketsuekium_tenshirium = new Item().setUnlocalizedName(name166).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_ketsuekium_onecrum = new Item().setUnlocalizedName(name167).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_ketsuekium_gold = new Item().setUnlocalizedName(name168).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_ketsuekium_iron = new Item().setUnlocalizedName(name169).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_shikyolt_sakuralt = new Item().setUnlocalizedName(name170).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_shikyolt_ayagrese = new Item().setUnlocalizedName(name171).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_shikyolt_tenshirium = new Item().setUnlocalizedName(name172).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_shikyolt_onecrum = new Item().setUnlocalizedName(name173).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_shikyolt_gold = new Item().setUnlocalizedName(name174).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_shikyolt_iron = new Item().setUnlocalizedName(name175).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_sakuralt_ayagrese = new Item().setUnlocalizedName(name176).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_sakuralt_tenshirium = new Item().setUnlocalizedName(name177).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_sakuralt_onecrum = new Item().setUnlocalizedName(name178).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_sakuralt_gold = new Item().setUnlocalizedName(name179).setTextureName(RPGOMain.MODID + ":" + name1).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_sakuralt_iron = new Item().setUnlocalizedName(name180).setTextureName(RPGOMain.MODID + ":" + name180).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_ayagrese_tenshirium = new Item().setUnlocalizedName(name181).setTextureName(RPGOMain.MODID + ":" + name181).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_ayagrese_onecrum = new Item().setUnlocalizedName(name182).setTextureName(RPGOMain.MODID + ":" + name182).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_ayagrese_gold = new Item().setUnlocalizedName(name183).setTextureName(RPGOMain.MODID + ":" + name183).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_ayagrese_iron = new Item().setUnlocalizedName(name184).setTextureName(RPGOMain.MODID + ":" + name184).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_tenshirium_onecrum = new Item().setUnlocalizedName(name185).setTextureName(RPGOMain.MODID + ":" + name185).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_tenshirium_gold = new Item().setUnlocalizedName(name186).setTextureName(RPGOMain.MODID + ":" + name186).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_tenshirium_iron = new Item().setUnlocalizedName(name187).setTextureName(RPGOMain.MODID + ":" + name187).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_onecrum_gold = new Item().setUnlocalizedName(name188).setTextureName(RPGOMain.MODID + ":" + name188).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_onecrum_iron = new Item().setUnlocalizedName(name189).setTextureName(RPGOMain.MODID + ":" + name189).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);
		mixedIngot_gold_iron = new Item().setUnlocalizedName(name190).setTextureName(RPGOMain.MODID + ":" + name190).setCreativeTab(RPGOMain.myTab).setMaxStackSize(64);

		GameRegistry.registerItem(mixedIngot_Xiatherium_Farunese, name1);
		GameRegistry.registerItem(mixedIngot_Xiatherium_Orobalt, name2);
		GameRegistry.registerItem(mixedIngot_Xiatherium_Kiritorium, name3);
		GameRegistry.registerItem(mixedIngot_Xiatherium_Asunalt, name4);
		GameRegistry.registerItem(mixedIngot_Xiatherium_eruslalt, name5);
		GameRegistry.registerItem(mixedIngot_Xiatherium_ithasium, name6);
		GameRegistry.registerItem(mixedIngot_Xiatherium_ozestum, name7);
		GameRegistry.registerItem(mixedIngot_Xiatherium_emodralt, name8);
		GameRegistry.registerItem(mixedIngot_Xiatherium_evosum, name9);
		GameRegistry.registerItem(mixedIngot_Xiatherium_nautrenese, name10);
		GameRegistry.registerItem(mixedIngot_Xiatherium_axespium, name11);
		GameRegistry.registerItem(mixedIngot_Xiatherium_ketsuekium, name12);
		GameRegistry.registerItem(mixedIngot_Xiatherium_shikyolt, name13);
		GameRegistry.registerItem(mixedIngot_Xiatherium_sakuralt, name14);
		GameRegistry.registerItem(mixedIngot_Xiatherium_ayagrese, name15);
		GameRegistry.registerItem(mixedIngot_Xiatherium_tenshirium, name16);
		GameRegistry.registerItem(mixedIngot_Xiatherium_onecrum, name17);
		GameRegistry.registerItem(mixedIngot_Xiatherium_gold, name18);
		GameRegistry.registerItem(mixedIngot_Xiatherium_iron, name19);
		GameRegistry.registerItem(mixedIngot_Farunese_Orobalt, name20);
		GameRegistry.registerItem(mixedIngot_Farunese_Kiritorium, name21);
		GameRegistry.registerItem(mixedIngot_Farunese_Asunalt, name22);
		GameRegistry.registerItem(mixedIngot_Farunese_eruslalt, name23);
		GameRegistry.registerItem(mixedIngot_Farunese_ithasium, name24);
		GameRegistry.registerItem(mixedIngot_Farunese_ozestum, name25);
		GameRegistry.registerItem(mixedIngot_Farunese_emodralt, name26);
		GameRegistry.registerItem(mixedIngot_Farunese_evosum, name27);
		GameRegistry.registerItem(mixedIngot_Farunese_nautrenese, name28);
		GameRegistry.registerItem(mixedIngot_Farunese_axespium, name29);
		GameRegistry.registerItem(mixedIngot_Farunese_ketsuekium, name30);
		GameRegistry.registerItem(mixedIngot_Farunese_shikyolt, name31);
		GameRegistry.registerItem(mixedIngot_Farunese_sakuralt, name32);
		GameRegistry.registerItem(mixedIngot_Farunese_ayagrese, name33);
		GameRegistry.registerItem(mixedIngot_Farunese_tenshirium, name34);
		GameRegistry.registerItem(mixedIngot_Farunese_onecrum, name35);
		GameRegistry.registerItem(mixedIngot_Farunese_gold, name36);
		GameRegistry.registerItem(mixedIngot_Farunese_iron, name37);
		GameRegistry.registerItem(mixedIngot_Orobalt_Kiritorium, name38);
		GameRegistry.registerItem(mixedIngot_Orobalt_Asunalt, name39);
		GameRegistry.registerItem(mixedIngot_Orobalt_eruslalt, name40);
		GameRegistry.registerItem(mixedIngot_Orobalt_ithasium, name41);
		GameRegistry.registerItem(mixedIngot_Orobalt_ozestum, name42);
		GameRegistry.registerItem(mixedIngot_Orobalt_emodralt, name43);
		GameRegistry.registerItem(mixedIngot_Orobalt_evosum, name44);
		GameRegistry.registerItem(mixedIngot_Orobalt_nautrenese, name45);
		GameRegistry.registerItem(mixedIngot_Orobalt_axespium, name46);
		GameRegistry.registerItem(mixedIngot_Orobalt_ketsuekium, name47);
		GameRegistry.registerItem(mixedIngot_Orobalt_shikyolt, name48);
		GameRegistry.registerItem(mixedIngot_Orobalt_sakuralt, name49);
		GameRegistry.registerItem(mixedIngot_Orobalt_ayagrese, name50);
		GameRegistry.registerItem(mixedIngot_Orobalt_tenshirium, name51);
		GameRegistry.registerItem(mixedIngot_Orobalt_onecrum, name52);
		GameRegistry.registerItem(mixedIngot_Orobalt_gold, name53);
		GameRegistry.registerItem(mixedIngot_Orobalt_iron, name54);
		GameRegistry.registerItem(mixedIngot_Kiritorium_Asunalt, name55);
		GameRegistry.registerItem(mixedIngot_Kiritorium_eruslalt, name56);
		GameRegistry.registerItem(mixedIngot_Kiritorium_ithasium, name57);
		GameRegistry.registerItem(mixedIngot_Kiritorium_ozestum, name58);
		GameRegistry.registerItem(mixedIngot_Kiritorium_emodralt, name59);
		GameRegistry.registerItem(mixedIngot_Kiritorium_evosum, name60);
		GameRegistry.registerItem(mixedIngot_Kiritorium_nautrenese, name61);
		GameRegistry.registerItem(mixedIngot_Kiritorium_axespium, name62);
		GameRegistry.registerItem(mixedIngot_Kiritorium_ketsuekium, name63);
		GameRegistry.registerItem(mixedIngot_Kiritorium_shikyolt, name64);
		GameRegistry.registerItem(mixedIngot_Kiritorium_sakuralt, name65);
		GameRegistry.registerItem(mixedIngot_Kiritorium_ayagrese, name66);
		GameRegistry.registerItem(mixedIngot_Kiritorium_tenshirium, name67);
		GameRegistry.registerItem(mixedIngot_Kiritorium_onecrum, name68);
		GameRegistry.registerItem(mixedIngot_Kiritorium_gold, name69);
		GameRegistry.registerItem(mixedIngot_Kiritorium_iron, name70);
		GameRegistry.registerItem(mixedIngot_Asunalt_eruslalt, name71);
		GameRegistry.registerItem(mixedIngot_Asunalt_ithasium, name72);
		GameRegistry.registerItem(mixedIngot_Asunalt_ozestum, name73);
		GameRegistry.registerItem(mixedIngot_Asunalt_emodralt, name74);
		GameRegistry.registerItem(mixedIngot_Asunalt_evosum, name75);
		GameRegistry.registerItem(mixedIngot_Asunalt_nautrenese, name76);
		GameRegistry.registerItem(mixedIngot_Asunalt_axespium, name77);
		GameRegistry.registerItem(mixedIngot_Asunalt_ketsuekium, name78);
		GameRegistry.registerItem(mixedIngot_Asunalt_shikyolt, name79);
		GameRegistry.registerItem(mixedIngot_Asunalt_sakuralt, name80);
		GameRegistry.registerItem(mixedIngot_Asunalt_ayagrese, name81);
		GameRegistry.registerItem(mixedIngot_Asunalt_tenshirium, name82);
		GameRegistry.registerItem(mixedIngot_Asunalt_onecrum, name83);
		GameRegistry.registerItem(mixedIngot_Asunalt_gold, name84);
		GameRegistry.registerItem(mixedIngot_Asunalt_iron, name85);
		GameRegistry.registerItem(mixedIngot_eruslalt_ithasium, name86);
		GameRegistry.registerItem(mixedIngot_eruslalt_ozestum, name87);
		GameRegistry.registerItem(mixedIngot_eruslalt_emodralt, name88);
		GameRegistry.registerItem(mixedIngot_eruslalt_evosum, name89);
		GameRegistry.registerItem(mixedIngot_eruslalt_nautrenese, name90);
		GameRegistry.registerItem(mixedIngot_eruslalt_axespium, name91);
		GameRegistry.registerItem(mixedIngot_eruslalt_ketsuekium, name92);
		GameRegistry.registerItem(mixedIngot_eruslalt_shikyolt, name93);
		GameRegistry.registerItem(mixedIngot_eruslalt_sakuralt, name94);
		GameRegistry.registerItem(mixedIngot_eruslalt_ayagrese, name95);
		GameRegistry.registerItem(mixedIngot_eruslalt_tenshirium, name96);
		GameRegistry.registerItem(mixedIngot_eruslalt_onecrum, name97);
		GameRegistry.registerItem(mixedIngot_eruslalt_gold, name98);
		GameRegistry.registerItem(mixedIngot_eruslalt_iron, name99);
		GameRegistry.registerItem(mixedIngot_ithasium_ozestum, name100);
		GameRegistry.registerItem(mixedIngot_ithasium_emodralt, name101);
		GameRegistry.registerItem(mixedIngot_ithasium_evosum, name102);
		GameRegistry.registerItem(mixedIngot_ithasium_nautrenese, name103);
		GameRegistry.registerItem(mixedIngot_ithasium_axespium, name104);
		GameRegistry.registerItem(mixedIngot_ithasium_ketsuekium, name105);
		GameRegistry.registerItem(mixedIngot_ithasium_shikyolt, name106);
		GameRegistry.registerItem(mixedIngot_ithasium_sakuralt, name107);
		GameRegistry.registerItem(mixedIngot_ithasium_ayagrese, name108);
		GameRegistry.registerItem(mixedIngot_ithasium_tenshirium, name109);
		GameRegistry.registerItem(mixedIngot_ithasium_onecrum, name110);
		GameRegistry.registerItem(mixedIngot_ithasium_gold, name111);
		GameRegistry.registerItem(mixedIngot_ithasium_iron, name112);
		GameRegistry.registerItem(mixedIngot_ozestum_emodralt, name113);
		GameRegistry.registerItem(mixedIngot_ozestum_evosum, name114);
		GameRegistry.registerItem(mixedIngot_ozestum_nautrenese, name115);
		GameRegistry.registerItem(mixedIngot_ozestum_axespium, name116);
		GameRegistry.registerItem(mixedIngot_ozestum_ketsuekium, name117);
		GameRegistry.registerItem(mixedIngot_ozestum_shikyolt, name118);
		GameRegistry.registerItem(mixedIngot_ozestum_sakuralt, name119);
		GameRegistry.registerItem(mixedIngot_ozestum_ayagrese, name120);
		GameRegistry.registerItem(mixedIngot_ozestum_tenshirium, name121);
		GameRegistry.registerItem(mixedIngot_ozestum_onecrum, name122);
		GameRegistry.registerItem(mixedIngot_ozestum_gold, name123);
		GameRegistry.registerItem(mixedIngot_ozestum_iron, name124);
		GameRegistry.registerItem(mixedIngot_emodralt_evosum, name125);
		GameRegistry.registerItem(mixedIngot_emodralt_nautrenese, name126);
		GameRegistry.registerItem(mixedIngot_emodralt_axespium, name127);
		GameRegistry.registerItem(mixedIngot_emodralt_ketsuekium, name128);
		GameRegistry.registerItem(mixedIngot_emodralt_shikyolt, name129);
		GameRegistry.registerItem(mixedIngot_emodralt_sakuralt, name130);
		GameRegistry.registerItem(mixedIngot_emodralt_ayagrese, name131);
		GameRegistry.registerItem(mixedIngot_emodralt_tenshirium, name132);
		GameRegistry.registerItem(mixedIngot_emodralt_onecrum, name133);
		GameRegistry.registerItem(mixedIngot_emodralt_gold, name134);
		GameRegistry.registerItem(mixedIngot_emodralt_iron, name135);
		GameRegistry.registerItem(mixedIngot_evosum_nautrenese, name136);
		GameRegistry.registerItem(mixedIngot_evosum_axespium, name137);
		GameRegistry.registerItem(mixedIngot_evosum_ketsuekium, name138);
		GameRegistry.registerItem(mixedIngot_evosum_shikyolt, name139);
		GameRegistry.registerItem(mixedIngot_evosum_sakuralt, name140);
		GameRegistry.registerItem(mixedIngot_evosum_ayagrese, name141);
		GameRegistry.registerItem(mixedIngot_evosum_tenshirium, name142);
		GameRegistry.registerItem(mixedIngot_evosum_onecrum, name143);
		GameRegistry.registerItem(mixedIngot_evosum_gold, name144);
		GameRegistry.registerItem(mixedIngot_evosum_iron, name145);
		GameRegistry.registerItem(mixedIngot_nautrenese_axespium, name146);
		GameRegistry.registerItem(mixedIngot_nautrenese_ketsuekium, name147);
		GameRegistry.registerItem(mixedIngot_nautrenese_shikyolt, name148);
		GameRegistry.registerItem(mixedIngot_nautrenese_sakuralt, name149);
		GameRegistry.registerItem(mixedIngot_nautrenese_ayagrese, name150);
		GameRegistry.registerItem(mixedIngot_nautrenese_tenshirium, name151);
		GameRegistry.registerItem(mixedIngot_nautrenese_onecrum, name152);
		GameRegistry.registerItem(mixedIngot_nautrenese_gold, name153);
		GameRegistry.registerItem(mixedIngot_nautrenese_iron, name154);
		GameRegistry.registerItem(mixedIngot_axespium_ketsuekium, name155);
		GameRegistry.registerItem(mixedIngot_axespium_shikyolt, name156);
		GameRegistry.registerItem(mixedIngot_axespium_sakuralt, name157);
		GameRegistry.registerItem(mixedIngot_axespium_ayagrese, name158);
		GameRegistry.registerItem(mixedIngot_axespium_tenshirium, name159);
		GameRegistry.registerItem(mixedIngot_axespium_onecrum, name160);
		GameRegistry.registerItem(mixedIngot_axespium_gold, name161);
		GameRegistry.registerItem(mixedIngot_axespium_iron, name162);
		GameRegistry.registerItem(mixedIngot_ketsuekium_shikyolt, name163);
		GameRegistry.registerItem(mixedIngot_ketsuekium_sakuralt, name164);
		GameRegistry.registerItem(mixedIngot_ketsuekium_ayagrese, name165);
		GameRegistry.registerItem(mixedIngot_ketsuekium_tenshirium, name166);
		GameRegistry.registerItem(mixedIngot_ketsuekium_onecrum, name167);
		GameRegistry.registerItem(mixedIngot_ketsuekium_gold, name168);
		GameRegistry.registerItem(mixedIngot_ketsuekium_iron, name169);
		GameRegistry.registerItem(mixedIngot_shikyolt_sakuralt, name170);
		GameRegistry.registerItem(mixedIngot_shikyolt_ayagrese, name171);
		GameRegistry.registerItem(mixedIngot_shikyolt_tenshirium, name172);
		GameRegistry.registerItem(mixedIngot_shikyolt_onecrum, name173);
		GameRegistry.registerItem(mixedIngot_shikyolt_gold, name174);
		GameRegistry.registerItem(mixedIngot_shikyolt_iron, name175);
		GameRegistry.registerItem(mixedIngot_sakuralt_ayagrese, name176);
		GameRegistry.registerItem(mixedIngot_sakuralt_tenshirium, name177);
		GameRegistry.registerItem(mixedIngot_sakuralt_onecrum, name178);
		GameRegistry.registerItem(mixedIngot_sakuralt_gold, name179);
		GameRegistry.registerItem(mixedIngot_sakuralt_iron, name180);
		GameRegistry.registerItem(mixedIngot_ayagrese_tenshirium, name181);
		GameRegistry.registerItem(mixedIngot_ayagrese_onecrum, name182);
		GameRegistry.registerItem(mixedIngot_ayagrese_gold, name183);
		GameRegistry.registerItem(mixedIngot_ayagrese_iron, name184);
		GameRegistry.registerItem(mixedIngot_tenshirium_onecrum, name185);
		GameRegistry.registerItem(mixedIngot_tenshirium_gold, name186);
		GameRegistry.registerItem(mixedIngot_tenshirium_iron, name187);
		GameRegistry.registerItem(mixedIngot_onecrum_gold, name188);
		GameRegistry.registerItem(mixedIngot_onecrum_iron, name189);
		GameRegistry.registerItem(mixedIngot_gold_iron, name190);
	}
}
